Custom Cookbook for Bluescape ELK

diff --git a/templates/default/elasticsearch.init.erb b/templates/default/elasticsearch.init.erb
--- a/templates/default/elasticsearch.init.erb
+++ b/templates/default/elasticsearch.init.erb
@@ -1,10 +1,9 @@
-#!/usr/bin/env bash
+#!/bin/bash
 #
-# elasticsearch
+# /etc/init.d/<%= node[:elasticsearch][:user] %> -- startup script for Elasticsearch
 #
-<% if node.platform_family?('debian') %>
 ### BEGIN INIT INFO
-# Provides:          elasticsearch
+# Provides:          <%= node[:elasticsearch][:user] %>
 # Required-Start:    $network $remote_fs $named
 # Required-Stop:     $network $remote_fs $named
 # Default-Start:     2 3 4 5
@@ -12,200 +11,198 @@
 # Short-Description: Starts elasticsearch
 # Description:       Starts elasticsearch using start-stop-daemon
 ### END INIT INFO
-<% else %>
-# chkconfig:   - 57 47
-# description: elasticsearch
-# processname: elasticsearch
-# config:      <%= node[:elasticsearch][:path][:conf] %>/elasticsearch.yml
-<% end %>
 
-# Source networking configuration
-#
-if [ -f /etc/sysconfig/network ]; then source /etc/sysconfig/network; fi
+PATH=/bin:/usr/bin:/sbin:/usr/sbin
+NAME=<%= node[:elasticsearch][:user] %>
+DESC="Elasticsearch Server"
+DEFAULT=/etc/default/$NAME
 
-# Set limits for environments ignoring `/etc/security/limits.d`
-#
-ulimit -n <%= node[:elasticsearch][:limits][:nofile] %>
-ulimit -l <%= node[:elasticsearch][:limits][:memlock] %>
+if [ `id -u` -ne 0 ]; then
+	echo "You need root privileges to run this script"
+	exit 1
+fi
 
-# Exit if networking is not up
-#
-[ "$NETWORKING" = "no" ] && exit
 
-PIDFILE='<%= node.elasticsearch[:pid_file] %>'
-ES_INCLUDE='<%= node.elasticsearch[:path][:conf] %>/elasticsearch-env.sh'
-CHECK_PID_RUNNING=$(ps ax | grep 'java' | grep -e "es.pidfile=$PIDFILE" | sed 's/^\s*\([0-9]*\)\s.*/\1/')
-RUBY_BIN=""
+. /lib/lsb/init-functions
 
-if command -v ruby >/dev/null 2>&1; then
-  RUBY_BIN=$(command -v ruby)
-  # ruby < 1.9 needs this, afterwards it doesn't work _at all_
-  if $RUBY_BIN -rubygems -e "puts Gem::VERSION" >/dev/null 2>&1; then
-    RUBY_BIN="$RUBY_BIN -rubygems "
+if [ -r /etc/default/rcS ]; then
+	. /etc/default/rcS
+fi
+
+
+# The following variables can be overwritten in $DEFAULT
+
+# Run Elasticsearch as this user ID and group ID
+ES_USER=<%= node[:elasticsearch][:user] %>
+ES_GROUP=<%= node[:elasticsearch][:user] %>
+
+# Directory where the Elasticsearch binary distribution resides
+ES_HOME=/usr/local/$NAME
+
+# Additional Java OPTS
+#ES_JAVA_OPTS=
+
+# Maximum number of open files
+MAX_OPEN_FILES='<%= node[:elasticsearch][:limits][:nofile] %>'
+
+# Maximum amount of locked memory
+MAX_LOCKED_MEMORY='<%= node[:elasticsearch][:limits][:memlock] %>'
+
+# Elasticsearch log directory
+LOG_DIR=/usr/local/log/$NAME
+
+# Elasticsearch data directory
+DATA_DIR=/usr/local/$NAME
+
+# Elasticsearch configuration directory
+CONF_DIR=/usr/local/$NAME
+
+# Maximum number of VMA (Virtual Memory Areas) a process can own
+MAX_MAP_COUNT=262144
+
+# Elasticsearch PID file directory
+PID_DIR="/var/local/var/run"
+
+# End of variables that can be overwritten in $DEFAULT
+
+# Overwrite settings from default file
+if [ -f "$DEFAULT" ]; then
+	. "$DEFAULT"
+fi
+
+# CONF_FILE setting was removed
+if [ ! -z "$CONF_FILE" ]; then
+    echo "CONF_FILE setting is no longer supported. elasticsearch.yml must be placed in the config directory and cannot be renamed."
+    exit 1
+fi
+
+# Define other required variables
+PID_FILE='$PID_DIR/<%= node.elasticsearch[:pid_file] %>'
+DAEMON=$ES_HOME/bin/elasticsearch
+DAEMON_OPTS="-d -p $PID_FILE -Edefault.path.logs=$LOG_DIR -Edefault.path.data=$DATA_DIR -Edefault.path.conf=$CONF_DIR"
+
+# This is the default env file with pre-configured parameters.
+ES_ENV_FILE='<%= node.elasticsearch[:path][:conf] %>/elasticsearch-env.sh'
+
+# Source the environment file
+if [ -n "$ES_ENV_FILE" ]; then
+  . "$ES_ENV_FILE"
+  if [ $? -ne 0 ]; then
+      echo "Unable to source environment file: $ES_ENV_FILE" >&2
+      exit 1
   fi
 fi
 
-start() {
-    if [ -f $PIDFILE ]; then
-      # PIDFILE EXISTS -- ES RUNNING?
-      echo -e "PID file found in $PIDFILE"
-      es_pid="$(cat $PIDFILE)"
-      pid_running="$( ps ax | grep 'java' | grep $es_pid )"
+export ES_JAVA_OPTS
+export ES_JVM_OPTIONS
+export JAVA_HOME
+export ES_INCLUDE
 
-      if [ ! -z "$pid_running" ] ; then
-        # EXIT IF ES IS ALREADY RUNNING
-	      echo -e "\033[31;1mPID $es_pid still alive, Elasticsearch already running...\033[0m"
-	      return 1
-      fi
-    fi
+if [ ! -x "$DAEMON" ]; then
+	echo "The elasticsearch startup script does not exists or it is not executable, tried: $DAEMON"
+	exit 1
+fi
 
-    echo -en "\033[1mStarting Elasticsearch...\033[0m"
-    touch $PIDFILE && chown <%= node[:elasticsearch][:user] %> $PIDFILE
-    <% if node.platform_family == 'debian' %>
-      ES_INCLUDE=$ES_INCLUDE start-stop-daemon --background --start --quiet --pidfile $PIDFILE --chuid <%= node[:elasticsearch][:user] %> --exec <%= node[:elasticsearch][:bindir] %>/elasticsearch -- -p $PIDFILE
-    <% else %>
-      su <%= node[:elasticsearch][:user] %> -c "ES_INCLUDE=$ES_INCLUDE <%= node[:elasticsearch][:bindir] %>/elasticsearch<%= node[:elasticsearch][:version] > '1' ? ' -d' : '' %> -p $PIDFILE"
-    <% end %>
+checkJava() {
+	if [ -x "$JAVA_HOME/bin/java" ]; then
+		JAVA="$JAVA_HOME/bin/java"
+	else
+		JAVA=`which java`
+	fi
 
-    if [ $? ]; then
-      echo -e " \e[32m[OK]\e[0m"
-    else
-      echo -e " \e[31m[FAILURE]\e[0m"
-    fi
-
-    return $?
+	if [ ! -x "$JAVA" ]; then
+		echo "Could not find any executable java binary. Please install java in your PATH or set JAVA_HOME"
+		exit 1
+	fi
 }
-
-stop() {
-    if [[ -f $PIDFILE ]]; then
-      echo -n -e "\033[1mStopping elasticsearch...\033[0m"
-
-      # REMOVE PIDFILE AND EXIT IF PROCESS NOT RUNNING
-      if [ ! $CHECK_PID_RUNNING ]; then
-        echo -e "\033[1mPID file found, but no matching process running?\033[0m"
-        echo    "Removing PID file..."
-        rm $PIDFILE
-        exit 0
-      fi
-
-      # KILL PROCESS
-      pid=$(cat $PIDFILE)
-      su <%= node[:elasticsearch][:user] %> -m -c "kill $(cat $PIDFILE)"
-      r=$?
-
-      # Check for process
-      timeout=0
-      while [ $(ps -p $pid | wc -l ) -gt '1' ]; do
-        echo -n '.'
-        (( timeout ++))
-        if [ $timeout -gt '30' ]; then return; fi
-        sleep 1
-      done
-
-      # Check for pidfile
-      timeout=0
-      while [ -f $PIDFILE  ]; do
-        echo -n '.'
-        (( timeout++ ))
-        if [ $timeout -gt '15' ]; then return; fi
-        sleep 1
-      done
-
-      echo;
-
-      return $r
-    else
-      echo -e "\033[1mNo PID file found -- elasticsearch not running?\033[0m"
-    fi
-}
-
-restart() {
-    stop
-    timeout=30
-    while ps aux | grep 'java' | grep -e "es.pidfile"; do
-      echo -n '.'
-      (( timeout-- ))
-      if [ $timeout -lt '1' ]; then return; fi
-      sleep 1
-    done;
-    start
-}
-
-status() {
-  # GOT PIDFILE?
-  [ -f $PIDFILE ] && pid=$(cat $PIDFILE)
-
-  # RUNNING
-  if [[ $pid && -d "/proc/$pid" ]]; then
-    if [ -z "$RUBY_BIN" ]; then
-      version=$(curl -s 'http://localhost:<%= node.elasticsearch[:http][:port] %>' | $RUBY_BIN -e 'require "json"; print JSON.parse(STDIN.read)["version"]["number"]')
-      echo -e "\033[1;37;46melasticsearch $version running with PID $pid\033[0m"
-    else
-      echo -e "\033[1;37;46melasticsearch running with PID $pid\033[0m"
-    fi
-    # VERBOSE
-    if [[ $pid && $1 == '-v' || $1 == '--verbose' ]]; then
-      if [ -z "$RUBY_BIN" ]; then
-        curl -s 'http://localhost:<%= node.elasticsearch[:http][:port] %>/_cluster/nodes/<%= node.elasticsearch[:node][:name] %>?os&process&jvm&network&transport&settings&pretty' | \
-        $RUBY_BIN -e '
-          begin
-            require "json"; h = JSON.parse(STDIN.read); id, node = h["nodes"].first;
-            def e(name, value); puts %Q|\e[1;36m#{(name.to_s+":").ljust(20)}\e[0m #{value || "N/A" rescue "N/A"}|; end
-            e "HTTP Address",  node["http_address"]
-            e "Node Name",     node["name"]
-            e "Cluster Name",  h["cluster_name"]
-            e "Started",       Time.at(node["jvm"]["start_time"].to_i/1000)
-            e "JVM",           "#{node["jvm"]["vm_name"]} (#{node["jvm"]["version"]})"
-            e "Memory Total",  node["os"]["mem"]["total"]
-            e "Open Files",    node["process"]["max_file_descriptors"]
-            e "Configuration", node["settings"]["config"]
-          rescue
-            puts "Metadata cannot be retrieved."
-          end
-        '
-      else
-        echo >&2 "verbose requires ruby but it is not installed"
-        exit 1
-      fi
-    fi
-    # INCORRECT PID?
-    if [ $pid != $CHECK_PID_RUNNING ]; then
-      echo -e "\033[1;31;40m[!] Incorrect PID found in $PIDFILE: $pid\033[0m"
-      return 1
-    fi
-    return 0
-  fi
-
-  # NOT RUNNING
-  if [[ ! $pid || ! -d "/proc/$pid" ]]; then
-    echo -e "\033[1;33;40melasticsearch not running\033[0m"
-    return 3
-  fi
-
-  # STALE PID FOUND
-  if [[ ! -d "/proc/$pid" && -f $PIDFILE ]]; then
-    echo -e "\033[1;31;40m[!] Stale PID found in $PIDFILE\033[0m"
-    return 1
-  fi
-}
-
 
 case "$1" in
   start)
-        start
-        ;;
+	checkJava
+
+	log_daemon_msg "Starting $DESC"
+
+	pid=`pidofproc -p $PID_FILE elasticsearch`
+	if [ -n "$pid" ] ; then
+		log_begin_msg "Already running."
+		log_end_msg 0
+		exit 0
+	fi
+
+	# Ensure that the PID_DIR exists (it is cleaned at OS startup time)
+	if [ -n "$PID_DIR" ] && [ ! -e "$PID_DIR" ]; then
+		mkdir -p "$PID_DIR" && chown "$ES_USER":"$ES_GROUP" "$PID_DIR"
+	fi
+	if [ -n "$PID_FILE" ] && [ ! -e "$PID_FILE" ]; then
+		touch "$PID_FILE" && chown "$ES_USER":"$ES_GROUP" "$PID_FILE"
+	fi
+
+	if [ -n "$MAX_OPEN_FILES" ]; then
+		ulimit -n $MAX_OPEN_FILES
+	fi
+
+	if [ -n "$MAX_LOCKED_MEMORY" ]; then
+		ulimit -l $MAX_LOCKED_MEMORY
+	fi
+
+	if [ -n "$MAX_MAP_COUNT" -a -f /proc/sys/vm/max_map_count ]; then
+		sysctl -q -w vm.max_map_count=$MAX_MAP_COUNT
+	fi
+
+	# Start Daemon
+	start-stop-daemon -d $ES_HOME --start -b --user "$ES_USER" -c "$ES_USER" --pidfile "$PID_FILE" --exec $DAEMON -- $DAEMON_OPTS
+	return=$?
+	if [ $return -eq 0 ]; then
+		i=0
+		timeout=10
+		# Wait for the process to be properly started before exiting
+		until { kill -0 `cat "$PID_FILE"`; } >/dev/null 2>&1
+		do
+			sleep 1
+			i=$(($i + 1))
+			if [ $i -gt $timeout ]; then
+				log_end_msg 1
+				exit 1
+			fi
+		done
+	fi
+	log_end_msg $return
+	exit $return
+	;;
   stop)
-        stop
-        ;;
-  restart)
-        restart
-        ;;
+	log_daemon_msg "Stopping $DESC"
+
+	if [ -f "$PID_FILE" ]; then
+		start-stop-daemon --stop --pidfile "$PID_FILE" \
+			--user "$ES_USER" \
+			--quiet \
+			--retry forever/TERM/20 > /dev/null
+		if [ $? -eq 1 ]; then
+			log_progress_msg "$DESC is not running but pid file exists, cleaning up"
+		elif [ $? -eq 3 ]; then
+			PID="`cat $PID_FILE`"
+			log_failure_msg "Failed to stop $DESC (pid $PID)"
+			exit 1
+		fi
+		rm -f "$PID_FILE"
+	else
+		log_progress_msg "(not running)"
+	fi
+	log_end_msg 0
+	;;
   status)
-        status $2
-        ;;
+	status_of_proc -p $PID_FILE elasticsearch elasticsearch && exit 0 || exit $?
+	;;
+  restart|force-reload)
+	if [ -f "$PID_FILE" ]; then
+		$0 stop
+	fi
+	$0 start
+	;;
   *)
-        echo $"Usage: $0 {start|stop|restart|status [-v]|}"
-        exit 1
+	log_success_msg "Usage: $0 {start|stop|restart|force-reload|status}"
+	exit 1
+	;;
 esac
 
-exit $?
+exit 0
